AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 120

# ====================================================
# Metrics Cops
# ====================================================
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Guardfile
